spring:
  datasource:
    platform: postgres
#    url: 'jdbc:postgresql://devedu-01.vm.cmx.ru:5432/postgres?currentSchema=vlutsenko'
    url: 'jdbc:postgresql://localhost:5432/postgres?currentSchema=vlutsenko'
    username: 'vlutsenko'
    password: 'vlutsenko'
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate.ddl-auto: none
  liquibase:
#    change-log: 'classpath:liquibase/db.changelog-master.xml'
    #url: 'jdbc:postgresql://devedu-01.vm.cmx.ru:5432/postgres?currentSchema=vlutsenko'
    url: 'jdbc:postgresql://localhost:5432/postgres?currentSchema=vlutsenko'
    user: 'vlutsenko'
    password: 'vlutsenko'
  kafka:
    consumer:
      bootstrap-servers: devedu-01.vm.cmx.ru:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: devedu-01.vm.cmx.ru:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  logging:
    level:
      com.querydsl.sql: DEBUG
      org.hibernate.SQL: DEBUG

